### PR TITLE
Handle singly tagged packets properly

### PR DESCRIPTION
**Pull request by jtroo**
Might need a version bump since the public fields of EthernetFrame have changed.

### CODE REVIEW

**Review by bestouff — APPROVED** [review]

**Comment by kpcyrd** [comment]
Correct, this needs a version bump :)

The functions to parse and convert `VidEthertype` can be rewritten to
```
named!(vid_ethertype<&[u8], VidEthertype>, do_parse!(
    vid: u16!(Big) >>
    et: ethertype >>
    (VidEthertype{vid, et})
));
```
The vlan thing is technically it's own header and wouldn't be parsed by the ethernet parser itself, but I don't have a strong opinion here. :)

**Comment by jtroo** [comment]
Changed the parsing into `VidEthertype` and also reverted the change to `EthernetFrame` to keep the same interface and performance. I should be better to keep the common use case the same.

**Comment by bestouff** [comment]
Would it be possible to remove the 'rustfmt' commit and rebase the last 2 ?  
I'd prefer to separate cosmetic changes from real code changes.

**Comment by jtroo** [comment]
Done, apart from one trailing space that my editor gets rid of automatically when saving. I could add it in some other editor, but hopefully this is fine.

**Comment by bestouff** [comment]
One more thing (sorry for nitpicking), please don't bump `Cargo.toml` I'll do it when I upload the crate. Probably after commiting a `rustfmt` pass if you don't send me a separate one :)

**Comment by jtroo** [comment]
No worries haha. Done!

**Comment by bestouff** [comment]
Ok, I merged your commit and released 0.4.1.  
I made a small mistake in the `README.md` which I fixed afterwards.  
Thanks !

**Pull request merged**
