### PR TITLE
Add arp support

### PR DESCRIPTION
**Pull request by kpcyrd**
This adds support for arp packets, including tests. This is based on the commit from #2 to make the tests happy.

### CODE REVIEW

**Comment by bestouff** [comment]
Looks good, thanks !

**Comment by kpcyrd** [comment]
@bestouff would you mind publishing a new version so I can update my dependency? :)

**Comment by bestouff** [comment]
Done (but I forgot to update the README with the nom version ...).
Is that OK with you ?

**Comment by kpcyrd** [comment]
@bestouff yes, thanks a lot :)

**Pull request merged**
