### PR TITLE
Port to nom4

### PR DESCRIPTION
**Pull request by kpcyrd**

### CODE REVIEW

**Comment by bestouff** [comment]
Thanks !

**Comment by kpcyrd** [comment]
I forgot to mention, the nom4 bump is a breaking change and should've been released as 0.3.0 :/ Can we yank 0.2.3 and re-release it as 0.3.0, as it breaks the public API of 0.2.x?

If in doubt, doing a 0.x.0 release is safer :)

**Comment by bestouff** [comment]
Oops my bad, I should have taken notice of this.
Should be fixed now, thanks.

**Comment by kpcyrd** [comment]
Perfect, thanks! :)

**Pull request merged**
